### ISSUE TITLE
Publish to Maven central using sbt-ci-release

### ISSUE THREAD

**Issue by mkurz** [lightbend/sbt-publish-rsync#6]
The artifacts of sbt-publish-rsync are only available on repo.scala-sbt.org currently which just had a multiple hours outage. There might come a time when repo.scala-sbt.org will not be available anymore. see https://github.com/sbt/sbt/issues/7202

**Comment by mkurz** [comment]
Pinging @johanandren @patriknw to get this going, also see
- https://github.com/akka/akka/issues/32300

**Comment by mkurz** [comment]
btw, it's used in various places:
- Akka: https://github.com/akka/akka/blob/62159d963fcacc47e0daa65fb2e1965488bfa110/project/plugins.sbt#L20
- Akka Http: https://github.com/akka/akka-http/blob/67c704111b755274e5daa423c2c923cbb017e8f9/project/plugins.sbt#L18
- Alpakka: https://github.com/akka/alpakka/blob/5d08fc258eba520d61333f9f0c93df211c8438d2/project/plugins.sbt#L14

**Comment by johanandren** [comment]
0.3 now on maven central
